name: Node.js

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run main.js
      run: node main.js
      env:
        API0_URL: ${{ secrets.API0_URL }}
        API0_KEY: ${{ secrets.API0_KEY }}

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gifts/
        git commit -m "^"
        git push
